# all available settings of specific linters
linters-settings:
  errcheck:
    ignore: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:Set

issues:
    exclude:
      - GetOkExists

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - vet
  disable-all: true
